"""Initial migration

Revision ID: 9bdf0ddfb761
Revises:
Create Date: 2026-05-04 16:00:52.795666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9bdf0ddfb761'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'result',
                    existing_type=sa.VARCHAR(),
                    type_=sa.JSON(),
                    existing_nullable=True,
                    postgresql_using="result::json"
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'result',
                    existing_type=sa.JSON(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    # ### end Alembic commands ###
