"""Add  field in Job model

Revision ID: b134372a5d4c
Revises: 9bdf0ddfb761
Create Date: 2026-05-05 16:29:55.125268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b134372a5d4c'
down_revision: Union[str, Sequence[str], None] = '9bdf0ddfb761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('file_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'file_metadata')
    # ### end Alembic commands ###
